In [1]:
import pandas as pd
import numpy as np

In [2]:
# DISTRIBUTIONS (NORMAL AND T)
from risk_management import distributions

# mu_vector, covariance_matrix = fit_multivariate_normal_dist(x: pd.DataFrame)

# mu, sigma, nu = fit_univariate_t_dist(x)

# alpha, betas, mu, sigma, nu = t_regression(X: pd.DataFrame, y:pd.Series, add_constant:bool = True, print_summary = False)

In [3]:
# MEASUREMENTS (CORRELATION, COVARIANCE, FACTORIZATIONS, RETURNS)
from risk_management import measurements

# corr = compute_correlation(x:pd.DataFrame, method="pearson", drop_missing = False, exponentially_weighted = False, lambda_ = 0.97, ddof: int =1)

# cov = compute_covariance(x:pd.DataFrame, drop_missing = False, exponentially_weighted = False, lambda_ = 0.97, ddof:int=1)

# cov = compute_covariance_with_ew_corr(x: pd.DataFrame, corr_lambda, var_lambda)

# psd = near_psd(A: pd.DataFrame, epsilon = 0.0)
# psd = higham_psd(A: pd.DataFrame, tolerance = 1e-8, max_iterations= 100_000)

# A = cholesky_factor(x:pd.DataFrame)

# returns = compute_returns(x: pd.DataFrame, return_type = "arithmetic")


In [4]:
# RISK METRICS (VAR, ES)
from risk_management import risk_metrics

# NOTE -> all of these assume that X was a set of RETURNS, not prices

# abs_VaR, rel_VaR = univariate_normal_VaR(mean: float, std: float, alpha = 0.05)

# nu, mu, sigma = t.fit(x)
# abs_VaR, rel_VaR = univariate_t_VaR(mu: float, sigma: float, nu: float, alpha: float = 0.05)

# abs_ES, diff_ES = expected_shortfall_normal(mu:float, sigma: float, alpha = 0.05)

# mu, sigma, nu = fit_univariate_t_dist(x)
# abs_ES, diff_ES = expected_shortfall_t(mu: float, sigma: float, nu: float, alpha: float = 0.05)

# delta_normal_var, delta normal ES

In [5]:
## SIMULATIONS
from risk_management import simulations

# NOTE -> all of these assume that X was a set of RETURNS, not prices

# simulation_data = normal_monte_carlo_simulation(mean_vector, covariance_matrix, n_sims, fix_method, seed=1234) # len(cov), n_sims

# simulation_data = pca_monte_carlo_simulation(mean_vector, covariance_matrix, n_sims, explained_threshold = 0.99, seed=1234) # len(cov), n_sims

# current_prices = vector of start prices of assets, holdings = vector of how many of each asset we have
# abs_VaR, rel_VaR = monte_carlo_VaR_sim(mean_vector, covariance_matrix, current_prices, holdings, n_draws, return_type = "arithmetic", alpha = 0.05, seed = 1234) 

# sim_dataframe = VaR_ES_2_level_sim_from_copula(sample_data: pd.DataFrame, holdings: np.array, prices: np.array, fix_method, n_sims = 100_000, alpha=0.05, seed=1234)

In [6]:
from risk_management import goodness_of_fit

# r2, adjr2, Aic, Aicc, BIC

from risk_management import asset_pricing

# European, American binary, American Discontinuous div

from risk_management import portfolio_construction

# risk parity, weighted risk parity, max sharpe

from risk_management import risk_attribution
# 


In [34]:
# data
means = np.array([0.14, 0.24, 0.29])
cov = np.array([[0.04, 0.04, 0.0],
                [0.04, 0.16, 0.1],
                [0.0, 0.1, 0.25]
            ])
r = 0.04
# weights all sum to 1

In [11]:
means, cov, r

(array([0.14, 0.24, 0.29]),
 array([[0.04, 0.04, 0.  ],
        [0.04, 0.16, 0.1 ],
        [0.  , 0.1 , 0.25]]),
 0.04)

### Question 1

In [35]:
# max sharpe ratio
weights = portfolio_construction.compute_max_sharpe_weights(means, cov, r)
weights

Optimization terminated successfully    (Exit mode 0)
            Current function value: -0.7071067811865476
            Iterations: 9
            Function evaluations: 36
            Gradient evaluations: 9


array([7.14285718e-01, 5.29395592e-23, 2.85714282e-01])

### Question 2

In [36]:
# risk parity portfolio
portfolio_construction.compute_risk_parity_weights(cov, risk_budgets=np.array([1,1,1]))

Optimization terminated successfully    (Exit mode 0)
            Current function value: 5.194434123128465e-18
            Iterations: 11
            Function evaluations: 44
            Gradient evaluations: 11


array([0.55853809, 0.21804668, 0.22341523])

### Question 3

In [38]:
# inverse volatility weights
stds = np.sqrt(cov.diagonal())
over_vol_sum = np.sum(1/stds)
weights = 1/stds * (1/over_vol_sum)
weights

array([0.52631579, 0.26315789, 0.21052632])

### Question 4

In [46]:
risk_budgets = np.array([1,1.5,1])
weights = portfolio_construction.compute_risk_parity_weights(cov, risk_budgets=risk_budgets)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 3.97068601349641e-18
            Iterations: 12
            Function evaluations: 48
            Gradient evaluations: 12


In [47]:
weights

array([0.51201872, 0.2831738 , 0.20480748])

In [41]:
vol = np.sqrt(weights.T.dot(cov).dot(weights))
csd = weights * (cov.dot(weights)) / vol
csd_budgeted = csd / risk_budgets

In [42]:
vol

np.float64(0.22814526012410366)

In [43]:
csd

array([0.07604842, 0.07604842, 0.07604842])

In [44]:
0.10232136/0.06821424

1.5

In [21]:
csd_budgeted

array([0.06821424, 0.06821424, 0.06821424])